name: Bundle Emotes

on:
  push:
    branches: [ main ]
    paths:
    - 'img/emotes/**'
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Zip Emotes
        uses: thedoctor0/zip-release@master
        with:
          filename: 'tinymotes.zip'
          directory: 'img/emotes'
      - name: Set Release Tag
        id: tagname
        run: echo "::set-output name=tagname::$(date +'tinymotes-%Y-%m-%d_%H-%M-%S')"
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tagname.outputs.tagname }}
          tag_name: ${{ steps.tagname.outputs.tagname }}
          files: img/emotes/tinymotes.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
